### PR TITLE
adding scrappy module and the first attempt to get data from the ogden

### PR DESCRIPTION
**Pull request by youngkingtut**
Added the scrappy module and a first attack at the ogden
you can run the following to get a file containing the json output:
scrappy crawl ogden -o items.json
This will output a json object containing upcoming concerts to the items.json file.

### CODE REVIEW

**Comment by ianstarz** [comment]
Woot! Awesome looks cool!

**Comment by ianstarz** [comment]
I'll give it a whirl when I get the chance, but since you've sliced it off into it's own top level, folder then I'm fine with you merging it in :+1:

**Comment by uberdwang** [comment]
Cool dood. I'll check it out too. Maybe in the future we make a dictionary containing spiders classes (ie ogden, bluebird, fillmore etc). That way our api can call Ogden, and it'll will up the dictionary and grab the ogden class.

**Comment by uberdwang** [comment]
I'm going to merge so I can also work with scrappy.

**Comment by ianstarz** [comment]
Boom awesome, sounds good! :+1:

_Ian Storz_
cirro
303.842.5224
wearecirro.com
@cirroweb https://twitter.com/cirroweb

2500 Larimer Street
#200
Denver, CO 80205

**Pull request merged**
